/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gerenciar;

import base_dados.BaseDados;
import com.itextpdf.text.BadElementException;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Image;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import funcao.Mensagem;
import funcao.Validacoes;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ji
 */
public class InterFrameGerenciarFesta extends javax.swing.JInternalFrame {

    private DefaultTableModel dtmCategoria;
    private DefaultTableModel dtmProduto;
    private int posFesta;

    public InterFrameGerenciarFesta() {
        initComponents();

        dtmCategoria = (DefaultTableModel) tableCategoria.getModel();
        dtmProduto = (DefaultTableModel) tableProduto.getModel();
        cbbFesta.setSelectedIndex(0);

        for (int i = 0; i < BaseDados.listaFesta.size(); i++) {
            cbbFesta.addItem(BaseDados.listaFesta.get(i).getNome());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        painelDeAbas = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        btnSalvarAlterCat = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCategoria = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        labelNomeFesta = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        labelNomeFesta2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnSalvarAlterProd = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableProduto = new javax.swing.JTable();
        txtSomaQtd = new javax.swing.JTextField();
        txtSomaPrecoUni = new javax.swing.JTextField();
        txtSomaPrecoTotal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtCaminho = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNomeArquivo = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        cbbFesta = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        painelDeAbas.setBackground(new java.awt.Color(0, 51, 102));

        jPanel4.setBackground(new java.awt.Color(0, 51, 102));

        btnSalvarAlterCat.setText("Salvar Alterações");
        btnSalvarAlterCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarAlterCatActionPerformed(evt);
            }
        });

        tableCategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Adicionar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableCategoria);
        if (tableCategoria.getColumnModel().getColumnCount() > 0) {
            tableCategoria.getColumnModel().getColumn(0).setMaxWidth(60);
            tableCategoria.getColumnModel().getColumn(1).setMinWidth(200);
            tableCategoria.getColumnModel().getColumn(2).setMinWidth(80);
        }

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Adicione as categorias de produtos mais convenientes:");

        labelNomeFesta.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelNomeFesta.setForeground(new java.awt.Color(204, 204, 204));
        labelNomeFesta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 0));
        jLabel6.setText("Caso retire uma categoria, todos os produtos da aba \"Produtos\" vinculados a essa categoria também serão excluídos.");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNomeFesta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 62, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvarAlterCat, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNomeFesta, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarAlterCat)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        painelDeAbas.addTab("Categorias", jPanel4);

        jPanel5.setBackground(new java.awt.Color(0, 51, 102));

        labelNomeFesta2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelNomeFesta2.setForeground(new java.awt.Color(204, 204, 204));
        labelNomeFesta2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Aplique as alterações feitas em seus produtos e refaça os cálculos com apenas 1 click:");

        btnSalvarAlterProd.setText("Salvar Alterações e Calcular Orçamento");
        btnSalvarAlterProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarAlterProdActionPerformed(evt);
            }
        });

        tableProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição", "Categoria", "Quantidade", "Valor Unitário", "Valor Total", "Remover"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableProduto);
        if (tableProduto.getColumnModel().getColumnCount() > 0) {
            tableProduto.getColumnModel().getColumn(0).setMaxWidth(60);
            tableProduto.getColumnModel().getColumn(1).setMinWidth(180);
            tableProduto.getColumnModel().getColumn(2).setMinWidth(140);
            tableProduto.getColumnModel().getColumn(3).setMinWidth(80);
        }

        txtSomaQtd.setEditable(false);

        txtSomaPrecoUni.setEditable(false);

        txtSomaPrecoTotal.setEditable(false);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Somatórios:");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 0));
        jLabel5.setText("Caso tenha excluído algum produto e quer adiciona-lo de volta, apenas click no botão \"Salvar Alterações\" na aba \"Categorias.\"");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 153, 0));
        jLabel7.setText("Após alterar um valor, pressione [Enter], para verificar se é um valor válido.");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 153, 0));
        jLabel8.setText("Utilize \".\"(ponto) ao invés de \",\"(vírgula).");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(txtSomaQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSomaPrecoUni, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSomaPrecoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNomeFesta2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalvarAlterProd))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNomeFesta2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvarAlterProd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSomaQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSomaPrecoUni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSomaPrecoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        painelDeAbas.addTab("Produtos", jPanel5);

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));

        jButton1.setText("Buscar Diretório");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("*Selecione um local para salvar o arquivo:");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("*Dê um nome para o seu relatório:");

        jButton2.setText("Gerar Relatório");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomeArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtCaminho, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addComponent(jLabel9)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(jButton2)))
                .addContainerGap(266, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCaminho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(39, 39, 39)
                .addComponent(jButton2)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        painelDeAbas.addTab("Gerar Relatório", jPanel2);

        cbbFesta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
        cbbFesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbFestaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Escolha a Fresta:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbbFesta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(painelDeAbas)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbFesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(painelDeAbas))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void preencherSomatório() {
        txtSomaQtd.setText(String.valueOf(BaseDados.listaFesta.get(posFesta).getSomaQtd()));
        txtSomaPrecoUni.setText(String.valueOf(BaseDados.listaFesta.get(posFesta).getSomaPrecoUnit()));
        txtSomaPrecoTotal.setText(String.valueOf(BaseDados.listaFesta.get(posFesta).getSomaPrecoTotal()));
    }

    private void cbbFestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbFestaActionPerformed
        dtmCategoria.setNumRows(0);
        dtmProduto.setNumRows(0);

        if (cbbFesta.getSelectedIndex() == 0) {
            btnSalvarAlterCat.setEnabled(false);
            tableCategoria.setEnabled(false);
            labelNomeFesta.setText("");

            btnSalvarAlterProd.setEnabled(false);
            tableProduto.setEnabled(false);
            labelNomeFesta2.setText("");
        } else {
            btnSalvarAlterCat.setEnabled(true);
            tableCategoria.setEnabled(true);
            btnSalvarAlterProd.setEnabled(true);
            tableProduto.setEnabled(true);
            
            boolean catAdicionada;

            posFesta = cbbFesta.getSelectedIndex() - 1;
            labelNomeFesta.setText(BaseDados.listaFesta.get(posFesta).getNome());
            labelNomeFesta2.setText(BaseDados.listaFesta.get(posFesta).getNome());

            for (int i = 0; i < BaseDados.listaCat.size(); i++) {
                if (BaseDados.listaCat.get(i).getTipoCategoria().equals("PRODUTO")) {
                    catAdicionada = false;

                    for (int j = 0; j < BaseDados.listaFesta.get(posFesta).listaCatProduto.size(); j++) {
                        if (BaseDados.listaFesta.get(posFesta).listaCatProduto.get(j).getCODIGO()
                                == BaseDados.listaCat.get(i).getCODIGO()) {

                            catAdicionada = true;
                        }
                    }
                    dtmCategoria.addRow(new Object[]{
                        BaseDados.listaCat.get(i).getCODIGO(),
                        BaseDados.listaCat.get(i).getNome(),
                        catAdicionada
                    });
                }
            }

            for (int i = 0; i < BaseDados.listaFesta.get(posFesta).listaCatProduto.size(); i++) {
                for (int j = 0; j < BaseDados.listaFesta.get(posFesta).listaProduto.size(); j++) {
                    if (BaseDados.listaFesta.get(posFesta).listaCatProduto.get(i).getCODIGO()
                            == BaseDados.listaFesta.get(posFesta).listaProduto.get(j).getCodCategoria()) {

                        dtmProduto.addRow(new Object[]{
                            BaseDados.listaFesta.get(posFesta).listaProduto.get(j).getCODIGO(),
                            BaseDados.listaFesta.get(posFesta).listaProduto.get(j).getNome(),
                            BaseDados.listaFesta.get(posFesta).listaCatProduto.get(i).getNome(),
                            BaseDados.listaFesta.get(posFesta).listaProduto.get(j).getQuantidade(),
                            BaseDados.listaFesta.get(posFesta).listaProduto.get(j).getPrecoUnitario(),
                            BaseDados.listaFesta.get(posFesta).listaProduto.get(j).getQuantidade()
                            * BaseDados.listaFesta.get(posFesta).listaProduto.get(j).getPrecoUnitario(),
                            false
                        });
                    }
                }
            }

            if (cbbFesta.getSelectedIndex() == 0) {
                btnSalvarAlterCat.setEnabled(false);
                btnSalvarAlterProd.setEnabled(false);
            } else {
                if (dtmCategoria.getRowCount() == 0) {
                    btnSalvarAlterCat.setEnabled(false);
                } else {
                    btnSalvarAlterCat.setEnabled(true);
                }
                if (dtmProduto.getRowCount() == 0) {
                    btnSalvarAlterProd.setEnabled(false);
                } else {
                    btnSalvarAlterProd.setEnabled(true);
                    preencherSomatório();
                }
            }
        }
    }//GEN-LAST:event_cbbFestaActionPerformed

    private void btnSalvarAlterCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarAlterCatActionPerformed
        if (Mensagem.confirmarSalvarAlter() == JOptionPane.YES_OPTION) {
            posFesta = cbbFesta.getSelectedIndex() - 1;
            int posCatProd;
            boolean achei;

            for (int i = 0; i < dtmCategoria.getRowCount(); i++) {
                achei = false;
                posCatProd = -1;
                int codCat = Integer.parseInt(dtmCategoria.getValueAt(i, 0).toString());

                if (BaseDados.listaFesta.get(posFesta).listaCatProduto.size() > 0) {
                    for (int j = 0; j < BaseDados.listaFesta.get(posFesta).listaCatProduto.size(); j++) {
                        if (BaseDados.listaFesta.get(posFesta).listaCatProduto.get(j).getCODIGO() == codCat) {
                            achei = true;
                            posCatProd = j;
                        }
                    }
                }

                if (achei && dtmCategoria.getValueAt(i, 2).equals(false)) {
                    for (int j = 0; j < BaseDados.listaFesta.get(posFesta).listaProduto.size(); j++) {
                        if (BaseDados.listaFesta.get(posFesta).listaCatProduto.get(posCatProd).getCODIGO()
                                == BaseDados.listaFesta.get(posFesta).listaProduto.get(j).getCodCategoria()) {

                            BaseDados.listaFesta.get(posFesta).listaProduto.remove(j);
                            j--;
                        }
                    }
                    BaseDados.listaFesta.get(posFesta).listaCatProduto.remove(posCatProd);

                } else if (!achei && dtmCategoria.getValueAt(i, 2).equals(true)) {
                    int posCatBusca = Validacoes.buscaCategoria(codCat);
                    BaseDados.listaFesta.get(posFesta).listaCatProduto.add(BaseDados.listaCat.get(posCatBusca));

                    for (int j = 0; j < BaseDados.listaProduto.size(); j++) {
                        if (BaseDados.listaCat.get(posCatBusca).getCODIGO()
                                == BaseDados.listaProduto.get(j).getCodCategoria()) {

                            BaseDados.listaFesta.get(posFesta).listaProduto.add(BaseDados.listaProduto.get(j));
                        }
                    }
                } else if (achei && dtmCategoria.getValueAt(i, 2).equals(true)) {
                    for (int j = 0; j < BaseDados.listaProduto.size(); j++) {
                        achei = false;
                        if (BaseDados.listaCat.get(i).getCODIGO()
                                == BaseDados.listaProduto.get(j).getCodCategoria()) {

                            for (int k = 0; k < BaseDados.listaFesta.get(posFesta).listaProduto.size(); k++) {
                                if (BaseDados.listaFesta.get(posFesta).listaProduto.get(k).getCODIGO()
                                        == BaseDados.listaProduto.get(j).getCODIGO()) {

                                    achei = true;
                                }
                            }
                            if (!achei) {
                                BaseDados.listaFesta.get(posFesta).listaProduto.add(BaseDados.listaProduto.get(j));
                            }
                        }
                    }
                }
            }
            cbbFestaActionPerformed(evt);
            Mensagem.sucessoSalvarAlter();
        }
    }//GEN-LAST:event_btnSalvarAlterCatActionPerformed

    private void btnSalvarAlterProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarAlterProdActionPerformed
        int qtd = 0, somaQtd = 0;
        int codCodProduto = -1;
        int posProduto = -1;
        double precoUni = 0, somaPrecoUni = 0, precoTotal = 0, somaPrecoTotal = 0;

        for (int i = 0; i < tableProduto.getRowCount(); i++) {
            if (dtmProduto.getValueAt(i, 6).equals(true)) {
                BaseDados.listaFesta.get(posFesta).listaProduto.remove(i);
                dtmProduto.removeRow(i);
                i--;
            } else {
                codCodProduto = Integer.parseInt(dtmProduto.getValueAt(i, 0).toString());
                posProduto = Validacoes.buscaProdutoFesta(posFesta, codCodProduto);

                qtd = Integer.parseInt(dtmProduto.getValueAt(i, 3).toString());
                precoUni = Double.parseDouble(dtmProduto.getValueAt(i, 4).toString().replace(",", "."));
                precoTotal = Double.parseDouble(dtmProduto.getValueAt(i, 5).toString().replace(",", "."));

                BaseDados.listaFesta.get(posFesta).listaProduto.get(posProduto).setQuantidade(qtd);
                BaseDados.listaFesta.get(posFesta).listaProduto.get(posProduto).setPrecoUnitario(precoUni);

                somaQtd += BaseDados.listaFesta.get(posFesta).listaProduto.get(posProduto).getQuantidade();
                somaPrecoUni += BaseDados.listaFesta.get(posFesta).listaProduto.get(posProduto).getPrecoUnitario();
                somaPrecoTotal += precoTotal;

                BaseDados.listaFesta.get(posFesta).setSomaQtd(somaQtd);
                BaseDados.listaFesta.get(posFesta).setSomaPrecoUnit(somaPrecoUni);
                BaseDados.listaFesta.get(posFesta).setSomaPrecoTotal(somaPrecoTotal);
            }
        }
        preencherSomatório();
        cbbFestaActionPerformed(evt);
        Mensagem.sucessoSalvarAlter();
    }//GEN-LAST:event_btnSalvarAlterProdActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser local = new JFileChooser();
        local.setDialogTitle("Selecione a pasta");
        local.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        int opcao = local.showOpenDialog(this);
        if (opcao == JFileChooser.APPROVE_OPTION) {
            File file = new File("caminho");
            file = local.getSelectedFile();
            String caminho = file.getAbsolutePath();
            txtCaminho.setText(caminho);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int nomeValido = 0;

        if (txtCaminho.getText().equals("") || txtNomeArquivo.getText().equals("")) {
            Mensagem.camposObrigatorios();
        } else {
            File salvarEscolhido = new File(txtCaminho.getText() + "\\" + txtNomeArquivo.getText() + ".pdf");
            if (salvarEscolhido.exists() == true) {
                nomeValido = JOptionPane.showConfirmDialog(rootPane, "Arquivo já existente, deseja substituir?", "Substituir", JOptionPane.YES_NO_OPTION);
            }
            if (nomeValido == JOptionPane.YES_OPTION) {
                Document doc = new Document(PageSize.A4);
                
                try {
                    PdfWriter pdf = PdfWriter.getInstance(doc, new FileOutputStream(txtCaminho.getText() + "\\" + txtNomeArquivo.getText() + ".pdf"));
                    doc.open();
                    Font fonte = new Font(Font.FontFamily.TIMES_ROMAN, 12, Font.BOLD);
                    
                    Paragraph cab = new Paragraph(cbbFesta.getSelectedItem().toString(), fonte);
                    cab.setAlignment(Element.ALIGN_CENTER);

                    //Imagem
                    Image imagem = null;
                    try {
                        imagem = Image.getInstance("/imagem/party_budget.png");
                    } catch (BadElementException | IOException ex) {
                        JOptionPane.showMessageDialog(rootPane, "erro: " + ex.getMessage());
                    }
                    imagem.scaleAbsolute(40, 55);
                    
                    PdfPTable tableCab = new PdfPTable(2);

                    tableCab.setWidths(new float[]{0.30f, 0.80f});
                    tableCab.setTotalWidth(550);
                    tableCab.setLockedWidth(true);
                    tableCab.getDefaultCell().setFixedHeight(70);
                    tableCab.getDefaultCell().setBorder(0);
                    tableCab.getDefaultCell().setPaddingRight(130);

                    tableCab.getDefaultCell().setHorizontalAlignment(Element.ALIGN_CENTER);
                    PdfPCell cellImagem = new PdfPCell(imagem);
                    cellImagem.setBorder(0);
                    tableCab.addCell(cellImagem);
                    tableCab.addCell(cab);
                    doc.add(tableCab);
                    
                    JOptionPane.showMessageDialog(rootPane, "Gerado com sucesso");
                    Desktop.getDesktop().open(new File(txtCaminho.getText() + "\\" + txtNomeArquivo.getText() + ".pdf"));
                    //PdfPTable table = new PdfPTable(6);
                    //table.setWidths(new int[]{60, 65, 45, 70, 70, 70, 70, 35});
                    
                } catch (FileNotFoundException ex) {
                    Mensagem.personalizada("Não foi possível gerar o relatório!");
                } catch (DocumentException ex) {
                    Mensagem.personalizada("Não foi possível gerar o relatório!");
                } catch (IOException ex) {
                    Logger.getLogger(InterFrameGerenciarFesta.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvarAlterCat;
    private javax.swing.JButton btnSalvarAlterProd;
    private javax.swing.JComboBox<String> cbbFesta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelNomeFesta;
    private javax.swing.JLabel labelNomeFesta2;
    private javax.swing.JTabbedPane painelDeAbas;
    private javax.swing.JTable tableCategoria;
    private javax.swing.JTable tableProduto;
    private javax.swing.JTextField txtCaminho;
    private javax.swing.JTextField txtNomeArquivo;
    private javax.swing.JTextField txtSomaPrecoTotal;
    private javax.swing.JTextField txtSomaPrecoUni;
    private javax.swing.JTextField txtSomaQtd;
    // End of variables declaration//GEN-END:variables
}
